spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: project

security:
  token:
    secret:
      key: KLDksffjds8409ufdfjsc9sudjkjcs

git:
  token: 707c22513445e8385625f2ae5aed7b071b8a4eed

server:
 port: 8082

logging:
  file: ../temp/logs/project-log.log
