spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: project

security:
  token:
    secret:
      key: KLDksffjds8409ufdfjsc9sudjkjcs

git:
  token: d83fb4a52706ce1400377a7313b47258ed4f6b71

server:
 port: 8082

logging:
  file: ../temp/logs/project-log.log
